Create metal.toml
streamlib/library pull request #1
Opened 2019-10-05 14:26 UTC by lunchboxav

Added a new library, filled with radio stream in genre of metal. Tested and it works fine, but please let me know if it doesn't work.

2019-10-05 20:49 UTC, yuvadm requested changes
Please fix the two syntax errors

I should probably set up a Github Action to do this automagically

2019-10-05 20:49 UTC, yuvadm commented on metal.toml
> +url = "http://5.135.154.69:11590/listen.pls
Missing `"`

2019-10-05 20:49 UTC, yuvadm commented on metal.toml
> +url = "http://23.29.71.154:8024/listen.pls"
Missing `"`

2019-10-06 02:42 UTC, lunchboxav commented
Oops sorry, I think I messed that file up before committing. Fixed that.

2019-10-06 05:00 UTC, merged